"""empty message

Revision ID: 54e11d1c85c7
Revises: 5bab4ccb8182
Create Date: 2018-08-31 20:47:42.818642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54e11d1c85c7'
down_revision = '5bab4ccb8182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ativo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ativo')
    # ### end Alembic commands ###
