"""empty message

Revision ID: 8b18924cdf2c
Revises: 583f8729b36b
Create Date: 2018-09-16 18:44:42.278767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b18924cdf2c'
down_revision = '583f8729b36b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipoRefeicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anamneses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('qtdAtividadeFisica', sa.Integer(), nullable=True),
    sa.Column('tipoExercicio', sa.String(length=150), nullable=True),
    sa.Column('horaAcorda', sa.TIME(), nullable=True),
    sa.Column('padraoRefeicao', sa.String(length=150), nullable=True),
    sa.Column('deficienciaAlimentacaoDiaria', sa.String(length=250), nullable=True),
    sa.Column('necessitaSuplementoAlimentar', sa.String(length=150), nullable=True),
    sa.Column('retencaoLiquido', sa.Boolean(), nullable=True),
    sa.Column('alergiaRemedio', sa.String(length=150), nullable=True),
    sa.Column('alergiaSuplemento', sa.String(length=150), nullable=True),
    sa.Column('intoleranciaAlimentar', sa.String(length=150), nullable=True),
    sa.Column('problemaSaude', sa.String(length=150), nullable=True),
    sa.Column('problemaSaudeFamilia', sa.String(length=150), nullable=True),
    sa.Column('medicacao', sa.String(length=150), nullable=True),
    sa.Column('suplementacao', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refeicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anamnese_id', sa.Integer(), nullable=False),
    sa.Column('tipoRefeicao_id', sa.Integer(), nullable=False),
    sa.Column('horario', sa.TIME(), nullable=False),
    sa.Column('refeicao', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['anamnese_id'], ['anamneses.id'], ),
    sa.ForeignKeyConstraint(['tipoRefeicao_id'], ['tipoRefeicoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refeicoes')
    op.drop_table('anamneses')
    op.drop_table('tipoRefeicoes')
    # ### end Alembic commands ###
